WEIGHT_UPPER_LIMIT  = 1.0
WEIGHT_LOWER_LIMIT  = -1.0
BIAS_UPPER_LIMIT    = 1.0
BIAS_LOWER_LIMIT    = -1.0
ACTIVE_CONNECTION_RATIO = 1.0
ACTIVE_CONNECTION_NUM_UPPER_LIMIT = 100 #invalid
ACTIVE_CONNECTION_NUM_LOWER_LIMIT = 1 #invalid
NEURON_NUM_UPPER_LIMIT = 10
NEURON_NUM_LOWER_LIMIT = 5

EPSILON = 0.1
GENERATION_NUM = 500
POPULATION_NUM = 50
LIFETIME_NUM = 100
ELITE_NUM = 4
MUTATION_PROB = 0.001
MUTATION_PROB_A = 0.01 #For FreeNetwork
MUTATION_PROB_B = 0.1 #For FreeNetwork

SEED =1000
