WEIGHT_UPPER_LIMIT  = 1.0
WEIGHT_LOWER_LIMIT  = -1.0
BIAS_UPPER_LIMIT    = 1.0
BIAS_LOWER_LIMIT    = -1.0
ACTIVE_CONNECTION_RATIO = 0.5
ACTIVE_CONNECTION_NUM_UPPER_LIMIT = 100
ACTIVE_CONNECTION_NUM_LOWER_LIMIT = 1

EPSILON = 0.1
GENERATION_NUM = 1000
POPULATION_NUM = 64
LIFETIME_NUM = 100
SEED =1000 
