WEIGHT_UPPER_LIMIT  = 1.0
WEIGHT_LOWER_LIMIT  = -1.0
BIAS_UPPER_LIMIT    = 1.0
BIAS_LOWER_LIMIT    = -1.0
ACTIVE_CONNECTION_RATIO = 0.1
ACTIVE_CONNECTION_NUM_UPPER_LIMIT = 100 #invalid
ACTIVE_CONNECTION_NUM_LOWER_LIMIT = 1 #invalid

EPSILON = 0.1
GENERATION_NUM = 500
POPULATION_NUM = 50
LIFETIME_NUM = 100
ELITE_NUM = 4
MUTATION_PROB = 0.001
SEED =1000
